# Scraper for the OCCRP web site.
# The goal is not to download all HTML, but only PDFs & other documents
# linked from the page as proof.
name: adres_grs

# A title for display in the UI:
description: 'streets from grs'

# Uncomment to run this scraper automatically:
schedule: monthly
delay: 1
stealthy: true
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: seed
    params:
      urls:
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=2
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=3
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=4
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=5
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=6
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=7
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=8
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=9
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=10
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=11
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=12
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=13
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=14
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=15
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=16
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=17
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=18
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=19
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=20
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=21
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=22
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=23
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=24
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=25
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=26
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=27
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=28
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=29
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=30
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=31
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=32
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=33
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=34
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=35
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=36
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=37
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=38
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=39
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=40
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=41
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=42
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=43
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=44
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=45
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=46
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=47
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=48
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=49
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=50
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=51
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=52
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=53
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=54
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=55
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=56
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=57
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=58
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=59
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=60
        - http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=61
        
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    params:
      # These rules specify which pages should be scraped or included:
      rules:
        or:
          - pattern: 'http://address.darek.gosreg.kg/'
          
                    
    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: parse
    params:
      store:
        and:
          - pattern: 'http://address.darek.gosreg.kg/'
          
    handle:
      # this makes it a recursive web crawler:
      store: extractdata
      fetch: fetch
  
  extractdata:
    # Parse the scraped pages to extract useful information
    method: example.adres_grs:extractdata
    handle:
      pass: store

  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "grs"
      unique:
        - number
    