# Scraper for the OCCRP web site.
# The goal is not to download all HTML, but only PDFs & other documents
# linked from the page as proof.
name: adres_grs

# A title for display in the UI:
description: 'streets from grs'

# Uncomment to run this scraper automatically:
schedule: monthly
delay: 1
stealthy: true
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: seed
    params:
      urls:
        # Osh streets
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=2
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=3
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=4
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=5
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=6
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=7
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=8
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=9
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=10
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=11
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=12
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=13
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=14
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=15
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=16
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=17
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=18
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=19
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=20
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=21
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=22
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=23
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=24
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=25
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=26
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=27
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=28
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=29
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=30
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=31
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=32
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=33
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=34
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=35
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=36
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=37
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=38
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=39
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=40
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=41
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=42
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=43
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=44
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=45
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=46
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=47
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=48
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=49
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=50
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=51
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=52
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=53
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=54
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=55
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=56
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=57
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=58
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=59
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=60
        #- http://address.darek.gosreg.kg/search/street/7412?streetType=0&streetName=&filter=sort&page=61
        # Bishkek streets
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=1
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=2
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=3
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=4
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=5
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=6
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=7
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=8
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=9
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=10
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=11
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=12
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=13
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=14
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=15
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=16
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=17
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=18
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=19
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=20
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=21
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=22
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=23
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=24
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=25
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=26
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=27
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=28
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=29
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=30
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=31
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=32
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=33
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=34
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=35
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=36
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=37
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=38
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=39
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=40
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=41
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=42
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=43
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=44
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=45
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=46
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=47
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=48
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=49
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=50
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=51
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=52
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=53
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=54
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=55
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=56
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=57
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=58
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=59
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=60
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=61
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=62
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=63
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=64
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=65
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=66
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=67
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=68
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=69
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=70
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=71
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=72
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=73
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=74
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=75
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=76
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=77
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=78
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=79
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=80
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=81
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=82
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=83
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=84
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=85
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=86
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=87
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=88
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=89
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=90
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=91
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=92
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=93
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=94
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=95
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=96
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=97
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=98
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=99
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=100
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=101
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=102
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=103
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=104
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=105
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=106
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=107
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=108
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=109
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=110
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=111
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=112
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=113
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=114
        - http://address.darek.gosreg.kg/search/street/7402?streetType=0&streetName=&filter=sort&page=115
        
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    params:
      # These rules specify which pages should be scraped or included:
      rules:
        or:
          - pattern: 'http://address.darek.gosreg.kg/'
          
                    
    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: parse
    params:
      store:
        and:
          - pattern: 'http://address.darek.gosreg.kg/'
          
    handle:
      # this makes it a recursive web crawler:
      store: extractdata
      fetch: fetch
  
  extractdata:
    # Parse the scraped pages to extract useful information
    method: example.adres_grs:extractdata
    handle:
      pass: store

  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "grs"
      unique:
        - number
    